# Generated by Django 5.0.3 on 2024-03-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_answerticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerticketmodel',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.supportmodel'),
        ),
    ]
