# Generated by Django 5.0.3 on 2024-03-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_answerticketmodel_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerTicketModel',
        ),
        migrations.DeleteModel(
            name='SupportModel',
        ),
    ]
