# Generated by Django 5.0.3 on 2024-03-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanswer',
            name='user',
        ),
    ]
