# Generated by Django 5.0.3 on 2024-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_ticket_status_alter_ticket_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanswer',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.CharField(default='4c1aa6f8', editable=False, max_length=8),
        ),
    ]
