# Generated by Django 5.0.3 on 2024-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.CharField(default='def5bc5d', editable=False, max_length=8),
        ),
    ]
