# Generated by Django 5.0.3 on 2024-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_ticket_status_alter_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.CharField(default='b86ee1fb', editable=False, max_length=8),
        ),
    ]
