# Generated by Django 5.0.3 on 2024-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_currency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ir_wallet',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
    ]
