# Generated by Django 5.0.3 on 2024-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_authentication',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('1', 'level1'), ('2', 'level2'), ('3', 'level3')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
