# Generated by Django 5.0.3 on 2024-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_irwallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authentication_image',
            field=models.ImageField(null=True, upload_to='user_info/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
