# Generated by Django 5.0.3 on 2024-03-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_currencywallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencywallet',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='currencys_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.currencywallet'),
        ),
    ]
