# Generated by Django 5.0.3 on 2024-03-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_currencywallet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currencys_wallet',
        ),
        migrations.AddField(
            model_name='currencywallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
