# Generated by Django 5.0.3 on 2024-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_customuser_currencys_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.DeleteModel(
            name='IrWallet',
        ),
    ]
