# Generated by Django 5.0.3 on 2024-03-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_customuser_balance_delete_irwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencywallet',
            name='code',
            field=models.CharField(default='68c3d051-6d9e-4a', max_length=16),
        ),
    ]
