# Generated by Django 5.0.3 on 2024-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_currency_currencywallet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencywallet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='currencywallet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='currencywallet',
            name='price',
        ),
        migrations.RemoveField(
            model_name='currencywallet',
            name='user',
        ),
        migrations.AddField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
