# Generated by Django 5.0.3 on 2024-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_currencywallet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('Level0', 'Level0'), ('Level1', 'Level1'), ('Level2', 'Level2'), ('Level3', 'Level3')], default=0, max_length=6, null=True),
        ),
    ]
