# Generated by Django 5.0.3 on 2024-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_buying_and_selling',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
