# Generated by Django 5.0.3 on 2024-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_adminsystemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsystemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
