# Generated by Django 5.0.3 on 2024-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_adminsystemmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsystemmodel',
            name='accept_or_reject',
            field=models.BooleanField(default=False),
        ),
    ]
