# Generated by Django 5.0.3 on 2024-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_adminsystemmodel_accept_or_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsystemmodel',
            name='accept_or_reject',
        ),
        migrations.AddField(
            model_name='adminsystemmodel',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=16, null=True),
        ),
    ]
