# Generated by Django 5.0.3 on 2024-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_remove_adminsystemmodel_accept_or_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsystemmodel',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=16, null=True),
        ),
    ]
