# Generated by Django 5.0.3 on 2024-04-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_adminsystemmodel_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSystemModel',
        ),
    ]
