# Generated by Django 5.0.3 on 2024-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_delete_adminsystemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbankmodel',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
