# Generated by Django 5.0.3 on 2024-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_cartbankmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='5371d26f-5', editable=False, max_length=10),
        ),
    ]
