# Generated by Django 5.0.3 on 2024-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_cartbankmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='c4be6ade-d', editable=False, max_length=10),
        ),
    ]
