# Generated by Django 5.0.3 on 2024-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_usermoreinfo_remove_customuser_authentication_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='more_info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='authentication_image',
            field=models.ImageField(null=True, upload_to='user_info/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='6c5321e1-9', editable=False, max_length=10),
        ),
        migrations.DeleteModel(
            name='UserMoreInfo',
        ),
    ]
