# Generated by Django 5.0.3 on 2024-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_remove_customuser_more_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsUserLevelCheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('national_code', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('authentication_image', models.ImageField(null=True, upload_to='user_info/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='bfdc6c18-1', editable=False, max_length=10),
        ),
    ]
