# Generated by Django 5.0.3 on 2024-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_delete_asuserlevelcheckmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='5d7a219b-f', editable=False, max_length=10),
        ),
    ]
