# Generated by Django 5.0.3 on 2024-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_alter_cartbankmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='41b01d7b-1', editable=False, max_length=10),
        ),
    ]
