# Generated by Django 5.0.3 on 2024-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_alter_cartbankmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbankmodel',
            name='uuid',
            field=models.CharField(default='e483eca5-c', editable=False, max_length=10),
        ),
    ]
