# Generated by Django 5.0.3 on 2024-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuserlevelcheckmodel',
            name='uuid',
            field=models.CharField(default='c21c615c-9', editable=False, max_length=10),
        ),
    ]
