# Generated by Django 5.0.3 on 2024-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_asuserlevelcheckmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuserlevelcheckmodel',
            name='uuid',
            field=models.CharField(default='1a2ad0a8-6', editable=False, max_length=10),
        ),
    ]
