# Generated by Django 5.0.3 on 2024-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_asuserlevel1checkmodel_asuserlevel2checkmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(default='d5640d98-3', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(default='f841d54b-9', editable=False, max_length=10),
        ),
    ]
