# Generated by Django 5.0.3 on 2024-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_asuserlevel1checkmodel_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(default='db420bda-b', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='authentication_image',
            field=models.ImageField(null=True, upload_to='as_level2_image/'),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(default='17ef0ae5-4', editable=False, max_length=10),
        ),
    ]
