# Generated by Django 5.0.3 on 2024-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_asuserlevel1checkmodel_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuserlevel1checkmodel',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asuserlevel2checkmodel',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(default='fafb58ec-0', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(default='e21afc09-d', editable=False, max_length=10),
        ),
    ]
