# Generated by Django 5.0.3 on 2024-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_asuserlevel1checkmodel_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuserlevel1checkmodel',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(default='574a9b89-7', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(default='aa0a0974-9', editable=False, max_length=10),
        ),
    ]
