# Generated by Django 5.0.3 on 2024-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_remove_asuserlevel1checkmodel_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(default='98a545ee-8', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(default='3108f2a7-5', editable=False, max_length=10),
        ),
    ]
