# Generated by Django 5.0.3 on 2024-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_asuserlevel1checkmodel_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuserlevel1checkmodel',
            name='uuid',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='asuserlevel2checkmodel',
            name='uuid',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
